deploy:
  stage: deploy
  image:
    name: alpine
    pull_policy: if-not-present
  before_script:
    - echo "Setting environment..."
    - apk add --no-cache sshpass openssh-client  # Installa sshpass e openssh-client
    - echo "SSH_USER: $SSH_USER"
    - echo "MACHINE_IP: $MACHINE_IP"

  script:
    - echo "Deploying application..."
    # Copia il file JAR al server remoto
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no target/*.jar $SSH_USER@$MACHINE_IP:/home/$SSH_USER/TRUCKPARKING.jar
    # Termina eventuali processi Java in esecuzione
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$MACHINE_IP 'killall java || true'
    # Avvia il JAR in background e redirige l'output
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$MACHINE_IP 'nohup java -jar /home/$SSH_USER/TRUCKPARKING.jar > /home/$SSH_USER/out.log 2>&1 &'
    - echo "Application successfully deployed."
