stages:
  - build

build:
  stage: build
  image:
    name: maven:3.8.2-openjdk-17
    pull_policy: if-not-present
  script:
    - echo "Compilando e installando Entities..."
    - cd Entities
    - mvn clean install
    - cd ..

    - echo "Compilando e installando Trucker..."
    - cd Trucker
    - mvn clean install
    - cd ..
  artifacts:
    paths:
      - Entities/target/*.jar
      - Trucker/target/*.jar
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
