stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: maven:3.8.2-openjdk-17
    pull_policy: if-not-present
  script:
    - echo "Compilando e installando il progetto multi-modulo..."
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

deploy:
  image:
    name: alpine
    pull_policy: if-not-present
  stage: deploy
  before_script:
    - echo "Setting environment..."
    - apk add sshpass
    - apk add openssh-client
    - eval $(ssh-agent -s)
      - ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$MACHINE_IP ls
      - sshpass -p $SSH_PASSWORD ssh-copy-id $SSH_USER@$MACHINE_IP
  script:
    - echo "Deploying application..."
    - scp target/*.jar $SSH_USER@$MACHINE_IP:/home/$SSH_USER/TRUCKPARKING.jar
    - echo $(ssh $SSH_USER@$MACHINE_IP 'killall java')
    #    - ssh $SSH_USER@$MACHINE_IP 'rm out.log'
    - ssh $SSH_USER@$MACHINE_IP 'nohup java -jar TRUCKPARKING.jar > out.log 2>&1 &'
    - echo "Application successfully deployed."








workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
