stages:
  - build

build:
  stage: build
  image:
    name: maven:3.8.2-openjdk-17
    pull_policy: if-not-present
  script:
    - echo "Compilando e installando il progetto multi-modulo..."
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
  only:
    - main
