stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: maven:3.8.2-openjdk-17
    pull_policy: if-not-present
  script:
    - echo "Compilando e installando il progetto multi-modulo..."
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  image:
    name: alpine
    pull_policy: if-not-present
  before_script:
    - echo "Setting environment..."
    - apk add --no-cache sshpass openssh-client  # Installa sshpass e openssh-client


  script:
    - echo "Deploying application..."
    # Copia il file JAR al server remoto
    - sshpass -p $SSH_PASSWORD scp -o StrictHostKeyChecking=no target/*.jar $SSH_USER@$MACHINE_IP:/home/$SSH_USER/TRUCKPARKING.jar
    # Termina eventuali processi Java in esecuzione
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$MACHINE_IP 'killall java || true'
    # Avvia il JAR in background e redirige l'output
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$MACHINE_IP 'nohup java -jar /home/$SSH_USER/TRUCKPARKING.jar > /home/$SSH_USER/out.log 2>&1 &'
    - echo "Application successfully deployed."


workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
